### ISSUE TITLE
源码

### ISSUE THREAD

**Issue by lihua12345667** [Echowinde/Echowinde.github.io#1]
大佬，复现E2GAN那篇blog写的清晰易懂，小白刚刚入门，能不能求下源码，好对照文章参考学习一下

**Comment by Echowinde** [comment]
[E2GAN.zip](https://github.com/Echowinde/Echowinde.github.io/files/15177069/E2GAN.zip)
过了很久了，可能有很多不对的地方，希望有帮助

**Comment by lihua12345667** [comment]
好的好的，谢谢大佬啦，祝工作学习顺利
